trigger:
  branches:
    include:
    - main

stages:
- stage: Build
  displayName: Build
  pool:
    vmImage: ubuntu-latest
  jobs:
  - job: Build
    displayName: Build
    steps:
    - task: DotNetCoreCLI@2
      displayName: Build Solution
      inputs:
        command: 'build'
        projects: 'TabsFormattingBug/TabsFormattingBug.csproj'
